# fly.toml app configuration file generated for big-two-app on 2024-11-10T17:11:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'big-two-app'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
