# fly.toml app configuration file generated for big-two on 2025-01-14T23:19:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'big-two'
primary_region = 'lhr'

[build]

[[mounts]]
destination = '/app/db'
source = 'big_two_db'

[http_service]
internal_port = 4321
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
[env]
BETTER_AUTH_URL = 'https://big-two.fly.dev'
BETTER_AUTH_SECRET = 'MSsXTsUHL6Jh0aAcN1Ls45NV30mY5GOa'
