# fly.toml app configuration file generated for pocketbase-snowy-meadow-4019 on 2024-11-04T18:24:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'big-two-pb'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
destination = "/pb/pb_data"
source = "pb_data"
